# Generated by Django 2.2.5 on 2019-11-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191113_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category'),
        ),
    ]
