# Generated by Django 2.2 on 2019-12-20 09:29

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20191220_1629'),
        ('order', '0002_auto_20191220_1629'),
        ('cart', '0002_auto_20191220_1629'),
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0002_auto_20191204_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUser',
            new_name='User',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
